### ISSUE TITLE
Library stopped working in january 2023

### ISSUE THREAD

**Issue by pgporfirio** [call-report/ffiec-data-connect#11]
Hi there,

I have bene uisng the library for the past 3 months. The code examples are excellent, but now it does nto work anymore. 

While the connection happens - using your example code and my password and username:

Credentials set from class initialization with username: pedroporfirio

        **HttpsConnection object properties:
        
        Https connection session is active
        
        
        proxy hostname = None
        proxy port = None
        proxy protocol = None
        is the proxy active? = False
        proxy username = None
        is proxy password set? = False**
        
Anytime I try to use any of the ohter functionalities (example retrieving the reporting dates avaliable):

from ffiec_data_connect import methods

reporting_periods = methods.collect_reporting_periods(
    session=conn,
    creds=creds,
    output_type="list",
    date_output_format="string_original"
)

print(reporting_periods[0:5])

the following error happens:

{
	"name": "Fault",
	"message": "The security token could not be authenticated or authorized ---> There is no row at position 0.",
	"stack": "---------------------------------------------------------------------------
Fault                                     Traceback (most recent call last)
Cell In[3], line 3
      1 from ffiec_data_connect import methods
----> 3 reporting_periods = methods.collect_reporting_periods(
      4     session=conn,
      5     creds=creds,
      6     output_type=\"list\",
      7     date_output_format=\"string_original\"
      8 )
     10 print(reporting_periods[0:5])

File ~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\ffiec_data_connect\\methods.py:277, in collect_reporting_periods(session, creds, series, output_type, date_output_format)
    274 ret = None
    276 if series == \"call\":
--> 277     ret = client.service.RetrieveReportingPeriods(dataSeries=\"Call\")
    278 elif series == \"ubpr\":
    279     ret = client.service.RetrieveUBPRReportingPeriods()

File ~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\zeep\\proxy.py:46, in OperationProxy.__call__(self, *args, **kwargs)
     43 if soap_headers:
     44     kwargs[\"_soapheaders\"] = soap_headers
---> 46 return self._proxy._binding.send(
     47     self._proxy._client,
     48     self._proxy._binding_options,
     49     self._op_name,
     50     args,
     51     kwargs,
     52 )

File ~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\zeep\\wsdl\\bindings\\soap.py:135, in SoapBinding.send(self, client, options, operation, args, kwargs)
    132 if client.settings.raw_response:
    133     return response
--> 135 return self.process_reply(client, operation_obj, response)

File ~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\zeep\\wsdl\\bindings\\soap.py:229, in SoapBinding.process_reply(self, client, operation, response)
    227 fault_node = doc.find(\"soap-env:Body/soap-env:Fault\", namespaces=self.nsmap)
    228 if response.status_code != 200 or fault_node is not None:
--> 229     return self.process_error(doc, operation)
    231 result = operation.process_reply(doc)
    233 if message_pack:

File ~\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\zeep\\wsdl\\bindings\\soap.py:329, in Soap11Binding.process_error(self, doc, operation)
    326     if child is not None:
    327         return child.text
--> 329 raise Fault(
    330     message=get_text(\"faultstring\"),
    331     code=get_text(\"faultcode\"),
    332     actor=get_text(\"faultactor\"),
    333     detail=fault_node.find(\"detail\", namespaces=fault_node.nsmap),
    334 )

Fault: The security token could not be authenticated or authorized ---> There is no row at position 0."
}

**Comment by mikehikes** [comment]
Hi! Thank you for your note and apologies for the late reply. Please be advised that users' experiences using the library in Windows have been very uneven. This is due to the libraries' hard dependency on the `zeep` library, which in turn depends on platform-dependent libraries in Windows that can be incompatible with zeep. I would advise using Google Colab, or any other Linux-based on MacOS-based OS to utilize the library.

I just tested access this morning via Colab and it worked fine. Feel free to try yourself here (replacing the user name nad password with your own): https://colab.research.google.com/drive/1pYt1QAyWTtBfK7yg1dp3ZKEx-x_ehlEb#scrollTo=EP75N5CDPGSB

**Comment by pgporfirio** [comment]
Awesome, thanks.

Weirdly enough I ended up solving it by creating a new key.

The API they have is a bit weird when they ask to use the password but it is actually the key you need to use!!! 😁






Pedro Porfirio

www.jabuticaba.app [Image] <https://uk.linkedin.com/in/pedroporfirio>



UK +44 752 532 8185

US +1 347 414 0544

Email ***@***.******@***.***>

________________________________

**Comment by mikehikes** [comment]
Glad that worked out! Cheers!
