### ISSUE TITLE
Error: No module named 'zoneinfo'

### ISSUE THREAD

**Issue by byu1999** [call-report/ffiec-data-connect#3]
I am working in Windows. It appears that I require tzdata in order to run zoneinfo in methods.py. I already have them both installed locally on my computer but still cannot seem to use the library. Any suggestions or potential fixes?

**Comment by mikehikes** [comment]
@byu1999, thanks for reporting the issue. If you could let me know the version of python you are using. I have not tested the package on a Windows computer, but my understanding of the dependencies involved with tzdata is that zoneinfo is provided only in python >= 3.9. (Although a backported package may be available).

In any case, I would recommend using anaconda/miniconda, venv, and/or your favorite python environment manager to create a new environment for ffiec-data-connect to ensure that the python executable, dependancies, and this package are all in the same path. 

(For venv, instructions for creating an environment are here: https://docs.python.org/3/library/venv.html - after creating and activating the environment, you may use a `pip install ffiec-data-connect` to re-install the package in that environment.

I've been in the process of updating this package, and a new version should be posted in the next couple of weeks. I'll leave this issue open as I will add additional dependency checks and minimum python version checks into the next version of this library. Once those checks are added (and hopefully after you've had a chance to try the above steps), I'll close out the issue.

**Comment by byu1999** [comment]
Thank you for the information. Turns out, I was working in Python 3.8. However, I followed your steps and am still unable to use the library. Now, my error seems to be a connection error. When running the example code from PyPI, below is the error: 

requests.exceptions.SSLError: HTTPSConnectionPool(host='cdr.ffiec.gov', port=443): Max retries exceeded with url: /Public/PWS/WebServices/RetrievalService.asmx?WSDL (Caused by SSLError(SSLCertVerificationError(1, '[SSL: 
CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

Is this an error in the actual library or just with my ability to connect with my FFIEC account? Any known fixes for these kinds of issues?

**Comment by mikehikes** [comment]
Hi @byu1999 - so, looks like I'm getting the same error. I did some digging (with `openssl s_client -connect cdr.ffiec.gov`) and saw that (using `openssl` installed via homebrew on MacOS Ventura) that the CA cert could not be verified, and thus an SSL connection could not be conducted.

However, it looks like the ca cert store on Ventura itself can validate the CA cert.

So, my hypothesis is that the FFIEC just switched out their CA for some reason, and that new CA has not been propagated through the ecosystem of packages/distributions.

It is possible to manually utilize a root CA cert, depending on your platform. Out of curiosity, what platform are you using to access? I could provide some more specific workarounds with that info. 

As reference, here is an excerpt of the output I received from openssl:

```
No client certificate CA names sent
Peer signing digest: SHA512
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2523 bytes and written 497 bytes
Verification error: unable to verify the first certificate
---
```

**Comment by byu1999** [comment]
Hi @mikehikes, I am currently working with a Windows operating system. I will look into the root CA cert that you mentioned earlier. Hopefully, that at least temporarily fixes the problem until a more permanent solution can be created. Thank you for all your help!

**Comment by mikehikes** [comment]
@byu1999 Looks like the CA issue was fixed. I just updated the version of this package with some additional bug fixes also. And, I updated the documentation to note that the security token is used as the credentials for the library, and _not_ the web account password.

Hopefully all these fixes combined fixed the issue you were having. Let me know if everything works now!

**Comment by byu1999** [comment]
Hi @mikehikes, it appears that the bug fixes are reflected on my end as well. However, I am having trouble with authentication. You mentioned "the security token is used as the credentials for the library". I have been attempting use my web account login. Where do I find or create my credentials for username and password?

**Comment by byu1999** [comment]
Hi @mikehikes, please ignore my previous comment. I have successfully connected, and it appears to be working! Your additional documentation on PyPI was very helpful. Feel free to close this issue. Thanks again!
